source 'https://rubygems.org'
gem 'rspec'
gem 'pg'
gem 'nokogiri'
gem 'rake'
gem 'standalone_migrations'
gem 'parallel'
gem 'anemone'

gem 'spork'
gem 'guard'
gem 'guard-rspec'
gem 'guard-spork'
