LIB_DIR = File.expand_path(File.dirname(__FILE__))
require 'optparse'
require 'pg'
require 'nokogiri'
require 'open-uri'
require 'date'
require 'standalone_migrations'
require 'parallel'
require 'kconv'
require 'rack'
require 'capybara'
require 'capybara/dsl'
require 'capybara/poltergeist'
require 'phantomjs'
require 'fileutils'
require 'selenium-webdriver'
require 'method_hooker'
require 'statsample'
require LIB_DIR + '/stock/db'
require LIB_DIR + '/stock/stocks'
require LIB_DIR + '/stock/stock_key'
require LIB_DIR + '/stock/stock'
require LIB_DIR + '/stock/split'
require LIB_DIR + '/stock/code'
require LIB_DIR + '/stock/date'
require LIB_DIR + '/stock/proxy'
require LIB_DIR + '/stock/yahoo'
require LIB_DIR + '/stock/k_db'
require LIB_DIR + '/stock/code_date'
require LIB_DIR + '/stock/code_time'
require LIB_DIR + '/stock/pair_time'
require LIB_DIR + '/stock/fx'
require LIB_DIR + '/stock/matsui'
require LIB_DIR + '/stock/smbc'
require LIB_DIR + '/stock/log'
require LIB_DIR + '/stock/order'
require LIB_DIR + '/stock/status'
require LIB_DIR + '/stock/player'
require LIB_DIR + '/stock/board'
require LIB_DIR + '/stock/hand'
require LIB_DIR + '/cluster/k-means'
require LIB_DIR + '/cluster/cluster'
require LIB_DIR + '/cluster/node'
require LIB_DIR + '/bayesian/node'
require LIB_DIR + '/bayesian/k2metric'
