development:
  adapter: postgresql
  host: 192.168.3.20
  encoding: utf8
  database: stock
  pool: 5
  username: akishige
  password: 135790

test:
  adapter: postgresql
  host: 192.168.3.20
  encoding: utf8
  database: stock
  pool: 5
  username: akishige
  password: 135790
